pipeline {
    agent any
    tools{
maven 'maven363'
} 
    stages {
        stage('Build') { 
            steps {
                sh 'cd SparkWordCount && mvn clean compile' 
            }
        }
        stage('Test') { 
            steps {
                sh 'cd SparkWordCount && mvn clean test'
            }
        }
        stage('Deploy') { 
            steps {
                sh 'cd SparkWordCount && mvn clean package'
            }
        }
    }
}

